version: '3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      - "SERVICES=${LOCALSTACK_SERVICES:-cloudformation,sqs,dynamodb}"
      - "DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      - "DOCKER_HOST=unix:///var/run/docker.sock"
      - "HOSTNAME=${LOCALSTACK_HOSTNAME:-localstack}"
      - "HOSTNAME_EXTERNAL=${LOCALSTACK_HOSTNAME_EXTERNAL:-localstack}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4565-4582:4565-4582"
      - "8080:8080"
    networks:
      - product-network

  setup:
    image: mesosphere/aws-cli
    container_name: setup-localstack
    volumes:
      - ./setup:/setup
    environment:
      AWS_ACCESS_KEY_ID: 1234
      AWS_SECRET_ACCESS_KEY: 1234
      AWS_DEFAULT_REGION: us-east-1
    depends_on:
      - localstack
    entrypoint: [ "" ]
    command: >
      sh -c "chmod +x /setup/setup.sh
      && /setup/setup.sh"
    networks:
      - product-network

  product-api:
    container_name: product-api
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    environment:
      - NODE_ENV=dev
      - DB_HOST=localstack
      - AWS_ACCESS_KEY_ID=1234
      - AWS_SECRET_ACCESS_KEY=1234
    volumes:
      - ./src:/home/node/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    links:
      - localstack
    depends_on:
      - localstack
    networks:
      - product-network

networks:
  product-network: