AWSTemplateFormatVersion: "2010-09-09"
Description: Template for Products API infrastructure
Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: productsTable
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 1

  productSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'domain-queue'
